### ISSUE TITLE
Em phải chỉnh sửa gì để cập nhật phiên bản mới ?

### ISSUE THREAD

**Issue by nvlong198** [greenglobal/zato-demo#1]
Chào anh @ndaidong, em mới làm quen với docker nên nhiều phần khá khó hiểu, phiên bản zato ở đây là 2.0 thì phải, giờ em muốn update zato & dependency lên bản mới hơn thì phải làm sao ạ ?
Em cám ơn

**Comment by ndaidong** [comment]
@nvlong198 chào bạn

Demo này chạy với docker image `ndaidong/zato:cluster`, base trên `ndaidong/zato:latest` chứa core Zato. Những images này đã outdated, nên để nâng cấp thì bạn cần dựa trên các dockerfiles trong repo này để tạo mới image theo ý bạn. Cụ thể như sau:

- Tạo mới image `nvlong/zato:core` cho phần core ESB Zato bằng cách chỉnh sửa [/core/Dockerfile](https://github.com/greenglobal/zato-demo/blob/master/core/Dockerfile)
- Tạo mới image `nvlong/zato:cluster` bằng cách chỉnh sửa [/cluster/Dockerfile](https://github.com/greenglobal/zato-demo/blob/master/cluster/Dockerfile)
- Cập nhật thông tin images mới vào [docker-compose.yml](https://github.com/greenglobal/zato-demo/blob/master/docker-compose.yml)

Sau đó run thử xem thế nào rồi cho mình biết.

**Comment by nvlong198** [comment]
@ndaidong 
Dạ `nvlong/zato:core`đầu tiên em sửa theo https://zato.io/docs/admin/guide/install/py3/ubuntu.html 
```
FROM ubuntu:18.04 as base

ENV LANG C.UTF-8

RUN apt-get update --fix-missing && apt-get upgrade -y && \
	apt-get install --no-install-recommends -y \
	apt-transport-https \
	software-properties-common && \
	add-apt-repository universe && \ 
	apt-get install tzdata && \
	curl -s https://zato.io/repo/zato-3.1-C9B13DF28CFE287D.pgp.txt | sudo apt-key add - && \
	add-apt-repository "deb [arch=amd64] https://zato.io/repo/stable/3.1/py3/ubuntu $(lsb_release -cs) main" && \
apt-get update && apt-get install -y zato && \
	cd /opt/zato/current && git checkout -- ./requirements.txt && \
	cd /home && rm -rf /var/lib/apt/lists/*

WORKDIR /home
```
`docker build -t nvlong/zato:core . `
mà khi em list các image lại không được image nvlong/zato ạ :disappointed: 
![image](https://user-images.githubusercontent.com/23328191/64261522-db022a00-cf56-11e9-9a4b-e0c1f0c50348.png)
Em thấy phức tạp ghê, ko biết anh có thể update mẫu lên repository này luôn được không ạ :sweat_smile:

**Comment by ndaidong** [comment]
@nvlong198 sau khi build thì bạn được 1 image chưa có tag name, bạn phải dùng lênh [docker tag](https://docs.docker.com/engine/reference/commandline/tag/) để  đặt tên cho nó. Ví dụ:

```
docker tag 45cb29827c69 nvlong/zato:core
```
Có thể đặt nhiều tags cho cùng 1 image:

```
docker tag 45cb29827c69 nvlong/zato:base
```

Thêm tag `latest` làm mặc định:

```
docker tag 45cb29827c69 nvlong/zato:latest
```

Sau đó bạn dùng lệnh [docker push](https://docs.docker.com/engine/reference/commandline/push/) để publish image này lên Docker Hub. Nếu chưa có account Docker Hub thì bạn phải [register](https://hub.docker.com/signup), sau đó login trên máy tính riêng bằng lệnh [docker login](https://docs.docker.com/engine/reference/commandline/login/)...
